version: '3'

services:
  consul:
    image: consul
    command: "consul agent -dev -client 0.0.0.0"
    ports:
      - "8500:8500"
    logging:
      driver: "none"

  web-app:
    image: jefferyb/polymer-cli
    command: "polymer serve -H 0.0.0.0"
    ports:
      - "8081:8081"
    volumes:
      - ./web-app/src:/home/polymer/app

  backend:
    image: backend
    build: ./backend
    volumes:
      - ./backend/src:/dotnetapp
    ports:
     - "5000:80"
    depends_on:
     - "consul"
