version: '3'

services:
  consul:
    image: consul
    command: "consul agent -dev -client 0.0.0.0"
    ports:
      - "8500:8500"

  web-app:
    image: jefferyb/polymer-cli
    command: "polymer serve -H 0.0.0.0"
    ports:
      - "8081:8081"
    volumes:
      - ./web-app/src:/home/polymer/app
    networks:
     - stitch-marker-network

  backend:
    image: backend
    build: ./backend/src/SM.Service
    volumes:
      - ./backend/src:/dotnetapp
    ports:
     - "5000:5000"
    depends_on:
     - "consul"
    networks:
     - stitch-marker-network

networks:
  stitch-marker-network:
    driver: bridge
